# 45장 프로미스

자바스크립트에서 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용한다. 콜백 패턴은 콜백헬로 가독성이 나쁘고, 비동기 처리 중 발생한 에러의 처리가 곤란하여 여러 비동기 처리를 한 번에 처리하는데도 한계가 있다.

ES6에서 비동기 처리를 위해 프로미스를 도입했다.

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

여기서 get은 비동기 함수다.

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 ㅇ낳고 즉시 종료된다.<br/>즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

GET요청을 전송하고 서버의 응답을 전달받는 get함수도 비동기 함수이다. 그 이유는 `**onload`이벤트 핸들러가 비동기로 동작하기 때문**이다. get함수를 호출하면 GET요청을 전송하고 onload 이벤트 핸들러를 등록한 다음 undefined를 반환 후 즉시 종료된다.

get이 응답 결과를 반환하게 수정해보자.

```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 반환한다.
      return JSON.parse(xhr.response);
    }
    console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

// ② id가 1인 post를 취득
const response = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response); // undefined
```

get함수가 호출되면   XMLHttpRequest객체를 생성하고, HTTP 요청을 초기화 후 HTTP요청을 전송한다. xhr.onload이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료하며, 이때 get함수에 명시적인 반환문이 없으므로 get함수는 undefined를 반환한다.

xhr.onload이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문은 get함수으 ㅣ반환문이 아니다. get함수는 반환문이 생략되었으므로 암묵적으로 undefined를 반환한다.

onload이벤트 핸들러는 get함수가 호출하지 않기 때문에 반환값을 캐치할 수 없다.

서버의 응답을 상위 스코프 변수에 할당해보자.

```js
let todos;

// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 상위 스코프의 변수에 할당한다.
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
console.log(todos); // ② undefined
```

xhr.onload이벤트 핸들러에서 서버응답을 상위 스코프의 변수에 할당하면 처리 순서가 보장되지 않는다.

서버로부터 응답이 도착하면 xhr객체에서 load이벤트가 발생한다. 이때 **xhr.load핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되는 것이 아니다.** xhr.onload이벤트 핸들러는 load이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다, 콜 스택이 비면 이벤트 루프에 의해 콜스택으로 푸시되어 실행된다.

이벤트 핸들러의 평가 -> 이벤트 핸들러의 실행 컨텍스트 생성 -> 콜 스택에 푸시 -> 이벤트 핸들러 실행과정을 거친다. xhr.onload이벤트 핸들러가 실행되는 시점에는 콜 스택이 빈  상태여야 하므로 2번의 console.log는 이미 종료된 후다.

**❗ 이처럼 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.**

따라서 비동기 함수의 처리 결과(서버응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 이때 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속처리를 수행하는 코랩ㄱ함수를 전달하는 것이 일반적이다.

```js
// GET 요청을 위한 비동기 함수
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      successCallback(JSON.parse(xhr.response));
    } else {
      // 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.
      failureCallback(xhr.status);
    }
  };
};

// id가 1인 post를 취득
// 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다.
get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

콜백 함수를 통해 비동기 처리 결과에 대한 후속처리를 수행하는 비동기 함수가 비동기 처리결과를 가지고 또다시 비동기 함수를 호출해야 한다면, 계속 중첩되면서 복잡도가 높아진다. 이를 **콜백 헬** 이라 부른다.

<br/>

### 45.1.2 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 문제점 중 가장 심각한게 에러 처리가 곤란하다는 것이다.

> try ... catch ... finally문
>
> try ... catch ... finally문을 실행하면 try 코드가 실행되고, 실행 중 발생하는 에러는 catch문의 err변수에 전달된다.finally는 에러 발생과 상관없이 반드시 한 번 실행된다.
>
> try ... catch ... finally문을 사용하면, 프로그램이 강제 종료되지 않는다.

```js
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

이 경우 catch블록에서 캐치되지 않는다.

setTimeout함수의 콜백 함수가 실행될 때 setTimeout함수는 이미 콜 스택에서 제거된 상태이다. 이것은 setTimeout함수의 콜백 함수를 호출한 것이 setTimeout함수가 아니라는 것을 의미한다. setTimeout함수의 콜백 함수의 호출자가 setTimeout함수라면 콜 스택의 현재 실행중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트 일때 현재 실행 중인 실행 컨텍스트의 하위 실행 컨텍스트가 setTimeout이어야 한다.

**에러는 호출자방향으로 전파된다.** 하지만 위의 경우 setTimeout함수의 콜백함수를 호출한 것은 setTimeout이 아니다. 따라서 setTimeout함수의 콜백함수가 발생시킨 에러 가 catch블록에서 캐치되지 않는다.

<br/><br/>

## 45.2 프로미스의 생성

Promise 생성자 함수를 new연산자와 함께 호출하면 프로미스 객체를 생성한다. ECMAScript사양에 정의된 표준 빌트인 객체이다.

**❗ Promise는 비동기 처리 상태와 처리 결과를 관리하는 객체이다.**

Promise생성자 함수는 비동기 처리를 수행할 콜백 함수 `resolve`와 `reject`함수를 인수로 전달받는다.

```js
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

비동기 처리 성공 시 resolve, 실패 시 reject함수를 호출한다.

```js
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```

* 비동기 처리 성공 : resolve함수를 호출해 프로미스를 fulfilled 상태로 변경한다.
* 비동기 처리 실패 : reject함수를 호출해 프로미스를 rejected상태로 변경한다.

`fulfilled`또는 `rejected`상태를 `settled`상태라 하며, pending이 아닌 상태로 비동기 처리가 수행된 상태를 말한다. `pending`에서 `settled`상태로 변경될 순 있지만, 일단 `settled`가 되면 다른 상태로 변화할 수 없다.

<br/><br/>

## 45.3 프로미스의 후속 처리 메서드

프로미스으 ㅣ후속처리르 ㄹ위해 `then`, `catch`, `finally`를 제공한다.

프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다. 모든 후속처리 메서드는 프로미스를 반환하며, 비동기로 동작한다.

### 45.3.1 Promise.prototype.then

then은 언제나 프로미스를 반환한다.

* 첫 번째 콜백 함수는 프로미스가 fulfilled상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달 받는다.
* 두 번째 콜백 함수는 프로미스가 rejected상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.

```js
// fulfilled
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

### 45.3.2 Promise.prototype.catch

catch메서드의 콜백 함수는 프로미스가 rejected상태인 경우만 호출된다.

```js
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)); // Error: rejected
```

catch는 then(undefined, onRejected)와 동일하게 동작하며, 언제나 Promise를 반환한다.

```js
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(undefined, e => console.log(e)); // Error: rejected
```

### 45.3.3 Promise.prototype.finally

finally는 성공(fulfilled)와 실패(rejected)와 상관없이 무조건 한 번 호출된다. 그렇기 떄문에 프로미스 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 떄 유용하다. 

finally도 언제나 프로미스를 반환한다.

```js
new Promise(() => {})
  .finally(() => console.log('finally')); // finally
```

<br/><br/>

## 45.4 프로미스의 에러 처리

프로미스가 제공하는 then, catch, finally를 사용하여 에러를 처리할 수 있다.

```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  res => console.log(res),
  err => console.error(err)
); // Error: 404
```

```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)); // Error: 404
```

then의 두번째 인수를 활용하는 것 보단 catch를 이용하는 것이 가독성에도 좋고, 명확하기 때문에 catch사용을 권장함.

<br/><br/>

## 45.5 프로미스 체이닝

then, catch, finally는 언제나 프로미스를 반환하기 때문에 연속호출을 할 수 있는데, 이를 `프로미스 체이닝`이라 한다. 프로미스가 아닌 값을 반환하더라도 그 값을 암묵적으로 resolve, 또는 reject하여 프로미스를 생성해 반환한다.

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 받아 후속 처리하기 때문에 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다. 다만, 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.

콜백 패턴은 가독성이 좋지 않은데, ES8에 도입된 **async/await**를 통해 해결할 수 있다.

```js
const url = 'https://jsonplaceholder.typicode.com';

(async () => {
  // id가 1인 post의 userId를 취득
  const { userId } = await promiseGet(`${url}/posts/1`);

  // 취득한 post의 userId로 user 정보를 취득
  const userInfo = await promiseGet(`${url}/users/${userId}`);

  console.log(userInfo);
})();
```

<br/><br/>

## 45.6 프로미스의 정적 메서드

Promise는 주로 생성자 함수로 사용되지만 함수도 객체이므로 메서드를 가질 수 있다.

### 45.6.1 Promise.resolve / Promise.reject

` Promise.resolve` / `Promise.reject`는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

각각 전달 받은 값을 `resolve`, `reject`하는 프로미스를 생성한다.

```js
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]

const resolvedPromise = new Promise(resolve => resolve([1, 2, 3]));
resolvedPromise.then(console.log); // [1, 2, 3]
```

```js
// 에러 객체를 reject하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error('Error!'));
rejectedPromise.catch(console.log); // Error: Error!

const rejectedPromise = new Promise((_, reject) => reject(new Error('Error!')));
rejectedPromise.catch(console.log); // Error: Error!
```

<br/>

### 45.6.2 Promise.all

여러개의 비동기 처리를 모두 병렬 처리할 떄 사용된다.

```js
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1()
  .then(data => {
    res.push(data);
    return requestData2();
  })
  .then(data => {
    res.push(data);
    return requestData3();
  })
  .then(data => {
    res.push(data);
    console.log(res); // [1, 2, 3] ⇒ 약 6초 소요
  })
  .catch(console.error);
```

이 예제는 3개의 비동기 처리를 순차적으로하는데, 서로 의존할 필요가 없기 때문에 Promise.all로 병렬처리 할 수 있다.

```js
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
  .catch(console.error);
```

❗ 전달받은 프로미스가 전부 fulfilled상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다. 또, 첫 번째 프로미스가 나중에 fulfilled상태가 되어도, resolve한 결과부터 차례대로 배열에 저장해  **처리 순서가 보장**된다.

대신 하나라도 rejected상태가되면 나머지가 fulfilled가 되는 것을 기다리지 않고 종료된다.

<br/>

### 45.6.3 Promise.race

Promise.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 드으이 이터러블을 인수로 전달 받는다. Promise.all과 다르게 모든 프로미스가 fulfilled상태가 되는 것을 기다리지 않고, 가장 먼저 fulfilled상태가 된 프로미스의 처리 결과를 reslove하는 새로운 프로미스를 반환한다.

```js
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000)) // 3
])
  .then(console.log) // 3
  .catch(console.log);
```

프로미스가 rejected 상태가 되면 Promise.all과 동일하게 처리된다. 하나라도 rejected되면 에러를 reject하는 새로운 프로미스를 반환한다.

```js
Promise.race([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
  .then(console.log)
  .catch(console.log); // Error: Error 3
```

<br/>

### 45.6.4 Promise.allSettled

전달받은 프로미스가 모두 settled상태가 되면 처리 결과를 배열로 반환된다.

ES11에 도입된 `Promise.allSettled`메서드는 IE를 제외한 모든 브라우저에서 지원한다.

```js
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error!')), 1000))
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

**`Promise.allSettled`메서드가 반환한 배열에는 `fulfilled`또는 `rejected`상태와는 상관없이 Promise.allSettled메서드가 받은 모든 프로미스들의 처리 결과가 담겨있다.**

* 프로미스가 fulfilled상태인 경우 비동기 처리 상태를 나타내는 status프로퍼티와 처리 결과를 나타내는 value프로퍼티를 갖는다.
* 프로미스가 rejected상태인 경우 비동기 처리 상태를 나타내는 status프로퍼티와 에러를 나타내는 reason프로퍼티를 갖는다.

```js
[
  // 프로미스가 fulfilled 상태인 경우
  {status: "fulfilled", value: 1},
  // 프로미스가 rejected 상태인 경우
  {status: "rejected", reason: Error: Error! at <anonymous>:3:60}
]
```

<br/><br/>

## 45.7 마이크로 태스크 큐

```js
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

1->2->3 순서로 동작할 거같지만 2->3->1 순서로 동작한다.<br/>프로미스의 후속 처리 메서드의 콜백함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장되기 때문이다.

`마이크로태스크 큐`는 태스크 큐와는 별도의 큐로 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다. 그외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.

콜백함수나 이벤트 핸들러를 일시 저장한다는 점에서 태스크 큐와 동일하지만 **마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.**

즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에 대기하고 있는 함수를 가져와 실행하고, 이후 마이크로태스크 큐가 비면 태스크 큐의 함수들을 실행시킨다.

<br/><br/>

### 45.8 fetch

`fetch함수`는 XMLHttpRequest객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API이다.

XMLHttpRequest객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

```js
const promise = fetch(url [, options])
```

**`fetch함수`는 HTTP 응답을 나타내느 Response객체를 래핑한 Promise객체를 반환한다.** 

```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => console.log(response));
```

Response.prototype에는 Response객체에 포함되어 있는 HTTP 응답 몸체를 위한 다양한 메서드를 제공한다. 예를들어, fetch함수가 반환한 프로미스가 래핑하고 있는 MIME타입이 application/json인 HTTP응답 몸체를 취득하려면 `Response.prototype.json`메서드를 사용한다. `Response.prototype.json`메서드느 ㄴResponse객체에서 HTTP응답 몸체를 취득하여 역직렬화 한다.

```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  // response는 HTTP 응답을 나타내는 Response 객체이다.
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then(response => response.json())
  // json은 역직렬화된 HTTP 응답 몸체이다.
  .then(json => console.log(json));
  // {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```

<br/>

fetch함수가 반환하는 프로미스는 기본적으로 `404 Not Found`나 `500 Internal Serve Error`같은 HTTP 에러가 발생해도 에러를 reject하지 않고, 불리언 타입의 ok상태를 false로 설정한 Response객체를 resolve한다. 오프라인 등의 네트워크 장애나 CORS에러에 의해 **요청이 완료되지 못한 경우에만 프로미스를 reject**한다.

fetch가 반환한 프로미스가 resolve한 불리언 타입의 ok상태르 ㄹ확인해 명시적으로 에러를 처리할 필요가 있다.

```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
  // response는 HTTP 응답을 나타내는 Response 객체다.
  .then(response => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todo => console.log(todo))
  .catch(err => console.error(err));
```

참고로 axios는 모든 HTTP에러를 reject하는 프로미스를 반환한다. 그렇기 때문에 모든 에러를 catch에서 처리할 수 있어 편리하다.